name: Push-to-EC2

on:
  push:
    branches: [ develop, DK* ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Deploy to my EC2 instance
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.RUNNER }}
        with:
          flags: '-avc --delete'
          src: 'dist/'
          dest: 'ubuntu@ec2-13-233-94-119.ap-south-1.compute.amazonaws.com:/var/www/html'


